//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesApp {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesApp.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione categoria.
        /// </summary>
        public static string cmbSelecionCategoria {
            get {
                return ResourceManager.GetString("cmbSelecionCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar reporte.
        /// </summary>
        public static string generarReporte {
            get {
                return ResourceManager.GetString("generarReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad:.
        /// </summary>
        public static string labelCantidad {
            get {
                return ResourceManager.GetString("labelCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria:.
        /// </summary>
        public static string labelCategoria {
            get {
                return ResourceManager.GetString("labelCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente: .
        /// </summary>
        public static string labelCliente {
            get {
                return ResourceManager.GetString("labelCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Producto:.
        /// </summary>
        public static string labelCodProducto {
            get {
                return ResourceManager.GetString("labelCodProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione fecha Final: .
        /// </summary>
        public static string labelFechaFin {
            get {
                return ResourceManager.GetString("labelFechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecione fecha inical: .
        /// </summary>
        public static string labelFechaInicio {
            get {
                return ResourceManager.GetString("labelFechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nit:.
        /// </summary>
        public static string labelNit {
            get {
                return ResourceManager.GetString("labelNit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string labelNombre {
            get {
                return ResourceManager.GetString("labelNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto:.
        /// </summary>
        public static string labelProducto {
            get {
                return ResourceManager.GetString("labelProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor:.
        /// </summary>
        public static string labelProveedor {
            get {
                return ResourceManager.GetString("labelProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad:.
        /// </summary>
        public static string labelUnidad {
            get {
                return ResourceManager.GetString("labelUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vlr Unitario:.
        /// </summary>
        public static string labelVlrUnitario {
            get {
                return ResourceManager.GetString("labelVlrUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese datos validos.
        /// </summary>
        public static string MessageCamposErroneos {
            get {
                return ResourceManager.GetString("MessageCamposErroneos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese cantidad valida, solo se admite numeros Enteros.
        /// </summary>
        public static string MessageCantidadNoValida {
            get {
                return ResourceManager.GetString("MessageCantidadNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoria de producto no se encuentra registrada.
        /// </summary>
        public static string MessageCategoriaNotExist {
            get {
                return ResourceManager.GetString("MessageCategoriaNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El codigo de producto ya existe.
        /// </summary>
        public static string MessageCodProductoExist {
            get {
                return ResourceManager.GetString("MessageCodProductoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible agregar datos.
        /// </summary>
        public static string MessageErrorEnInsercion {
            get {
                return ResourceManager.GetString("MessageErrorEnInsercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La identificacion de este cliente ya esta registrado pertenece a: .
        /// </summary>
        public static string MessageIdClienteExist {
            get {
                return ResourceManager.GetString("MessageIdClienteExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La identifiacion de este proveedor ya esta registrado pertenece a: .
        /// </summary>
        public static string MessageIdProveedorExist {
            get {
                return ResourceManager.GetString("MessageIdProveedorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaccion exitosa.
        /// </summary>
        public static string MessageInsercionExitosa {
            get {
                return ResourceManager.GetString("MessageInsercionExitosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay disponible una cantidad tan grande en bodega.
        /// </summary>
        public static string MessageNohayCantidadSuficiente {
            get {
                return ResourceManager.GetString("MessageNohayCantidadSuficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta categoria ya se encuentra registrada, :.
        /// </summary>
        public static string MessageNombreCategoriaExist {
            get {
                return ResourceManager.GetString("MessageNombreCategoriaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producto No existe, registrelo primero.
        /// </summary>
        public static string MessageProductoNotExist {
            get {
                return ResourceManager.GetString("MessageProductoNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proveedor no se encuentra registrado.
        /// </summary>
        public static string MessageProveedorNotExist {
            get {
                return ResourceManager.GetString("MessageProveedorNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos.
        /// </summary>
        public static string tabIngreso {
            get {
                return ResourceManager.GetString("tabIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias.
        /// </summary>
        public static string tabPreferencias {
            get {
                return ResourceManager.GetString("tabPreferencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        public static string tabReportes {
            get {
                return ResourceManager.GetString("tabReportes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas.
        /// </summary>
        public static string tabSalidas {
            get {
                return ResourceManager.GetString("tabSalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar Imagen.
        /// </summary>
        public static string textinsertImagen {
            get {
                return ResourceManager.GetString("textinsertImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string textoIngresar {
            get {
                return ResourceManager.GetString("textoIngresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresos.
        /// </summary>
        public static string textoIngresos {
            get {
                return ResourceManager.GetString("textoIngresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salidas.
        /// </summary>
        public static string textoSalida {
            get {
                return ResourceManager.GetString("textoSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        public static string textPwd {
            get {
                return ResourceManager.GetString("textPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string textUsuario {
            get {
                return ResourceManager.GetString("textUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de categorias.
        /// </summary>
        public static string titleIngresocategoria {
            get {
                return ResourceManager.GetString("titleIngresocategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso de clientes.
        /// </summary>
        public static string titleIngresoClientes {
            get {
                return ResourceManager.GetString("titleIngresoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso de productos.
        /// </summary>
        public static string titleIngresoProducto {
            get {
                return ResourceManager.GetString("titleIngresoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingreso de Proveedores.
        /// </summary>
        public static string titleIngresoProveedor {
            get {
                return ResourceManager.GetString("titleIngresoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Ingresos.
        /// </summary>
        public static string titleIngresos {
            get {
                return ResourceManager.GetString("titleIngresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string titlelogin {
            get {
                return ResourceManager.GetString("titlelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de Salidas.
        /// </summary>
        public static string titleSalidas {
            get {
                return ResourceManager.GetString("titleSalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control Inventario.
        /// </summary>
        public static string titleVentana {
            get {
                return ResourceManager.GetString("titleVentana", resourceCulture);
            }
        }
    }
}
